apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  labels:
    app: php-http-vars
    app.kubernetes.io/component: php-http-vars
    app.kubernetes.io/instance: php-http-vars
    app.kubernetes.io/name: php-http-vars
    app.openshift.io/runtime: php
    app.openshift.io/runtime-version: 7.4-ubi8
  name: php-http-vars
spec:
  failedBuildsHistoryLimit: 2
  successfulBuildsHistoryLimit: 2
  nodeSelector: null
  output:
    to:
      kind: ImageStreamTag
      name: php-http-vars:latest
  runPolicy: Serial
  source:
    contextDir: /
    git:
      uri: https://github.com/brunobenchimol/php-http-vars
    type: Git
  strategy:
    sourceStrategy:
      from:
        kind: ImageStreamTag
        name: php:7.4-ubi8
        namespace: openshift
    type: Source
  triggers:
  - imageChange: {}
    type: ImageChange
  - type: ConfigChange