#---
#apiVersion: kustomize.config.k8s.io/v1beta1
#kind: Kustomization

resources:
  - namespace.yaml
  - buildconfig.yaml
  - deployment.yaml
  - service.yaml
  - route.yaml

replacements:
  - path: registry-path.yaml
