#---
#apiVersion: kustomize.config.k8s.io/v1beta1
#kind: Kustomization

resources:
  - namespace.yaml
  - tekton-ci/ci-pvc.yaml
  - tekton-ci/ci-pipeline-s2i-build.yaml
  - deployment.yaml
  - service.yaml
  - route.yaml

replacements:
  - path: replacements.yaml
