#---
#apiVersion: kustomize.config.k8s.io/v1beta1
#kind: Kustomization

resources:
  - namespace.yaml
  - tekton-ci/01-ci-pvc.yaml
  - tekton-ci/02-ci-pipeline-s2i-build.yaml
  - imagestreamtag.yaml
  - deployment.yaml
  - service.yaml
  - route.yaml

replacements:
  - path: replacements.yaml

configMapGenerator:
- name: php-http-vars-configmap
  literals:
  - CUSTOM_VAR=sample
  options:
    disableNameSuffixHash: true

secretGenerator:
- name: php-http-vars-secret
  literals:
  - SECRET_VAR=sample
  options:
    disableNameSuffixHash: true