#---
#apiVersion: kustomize.config.k8s.io/v1beta1
#kind: Kustomization

resources:
  - namespace.yaml
  - tekton-ci/01-ci-pvc.yaml
  - tekton-ci/02-ci-pipeline-s2i-build.yaml
  - imagestreamtag.yaml
  - deployment.yaml
  - service.yaml
  - route.yaml
  - webhook/01-triggertemplate.yaml
  - webhook/02-eventlistener.yaml
  - webhook/03-config-logging-triggers.yaml
  - webhook/04-el-deployment.yaml
  - webhook/05-el-svc.yaml
  - webhook/06-el-route.yaml

replacements:
  - path: replacements.yaml

configMapGenerator:
- name: php-http-vars-configmap
  literals:
  - CUSTOM_VAR=sample
  options:
    disableNameSuffixHash: true

secretGenerator:
- name: php-http-vars-secret
  literals:
  - SECRET_VAR=verysecret
  options:
    disableNameSuffixHash: true