apiVersion: triggers.tekton.dev/v1alpha1
kind: EventListener
metadata:
  finalizers:
    - eventlisteners.triggers.tekton.dev
  name: event-listener-php-http-vars
spec:
  namespaceSelector: {}
  resources: {}
  serviceAccountName: pipeline
  triggers:
    - bindings:
        - kind: ClusterTriggerBinding
          ref: github-push
      template:
        ref: trigger-template-php-http-vars-ci