kind: ConfigMap
apiVersion: v1
metadata:
  name: config-logging-triggers
data:
  loglevel.eventlistener: info
  zap-logger-config: >-
    {"level": "info","development": false,"sampling": {"initial":
    100,"thereafter": 100},"outputPaths": ["stdout"],"errorOutputPaths":
    ["stderr"],"encoding": "json","encoderConfig": {"timeKey": "ts","levelKey":
    "level","nameKey": "logger","callerKey": "caller","messageKey":
    "msg","stacktraceKey": "stacktrace","lineEnding": "","levelEncoder":
    "","timeEncoder": "iso8601","durationEncoder": "","callerEncoder": ""}}
