kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: el-php-http-vars
  labels:
    app.kubernetes.io/managed-by: EventListener
    app.kubernetes.io/part-of: Triggers
    eventlistener: event-listener-php-http-vars
spec:
  to:
    kind: Service
    name: svc-el-php-http-vars
    weight: 100
  port:
    targetPort: 8080
  tls:
    termination: edge
  wildcardPolicy: None