apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  labels:
    app: php-http-vars
    app.kubernetes.io/component: php-http-vars
    app.kubernetes.io/instance: php-http-vars
    app.kubernetes.io/name: php-http-vars
    app.openshift.io/runtime: php
    app.openshift.io/runtime-version: 7.4-ubi8
  name: php-http-vars
spec:
  failedBuildsHistoryLimit: 2
  successfulBuildsHistoryLimit: 2
  nodeSelector: null
  output:
    to:
      kind: ImageStreamTag
      name: php-http-vars:latest
    pushSecret:
      name: builder-dockercfg-pqwf7
  runPolicy: Serial
  source:
    contextDir: /
    git:
      uri: https://github.com/brunobenchimol/php-http-vars
    type: Git
  strategy:
    sourceStrategy:
      from:
        kind: DockerImage
        name: >-
          image-registry.openshift-image-registry.svc:5000/openshift/php@sha256:696a1dc9240b68114cf5998412f116056ada4ffda2e9c9a6281e6eac7fccaf66
      pullSecret:
        name: builder-dockercfg-pqwf7
    serviceAccount: builder
    type: Source
  triggers:
  - imageChange: {}
    type: ImageChange
  - type: ConfigChange