apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: php-http-vars-ci
spec:
  params:
   - name: GIT_URL
     default: 'https://github.com/brunobenchimol/php-http-vars'
   - name: GIT_REPO_NAME
     default: 'php-http-vars'
   - name: GIT_BRANCH
     default: 'main' 
   - name: GIT_PATH_CONTEXT
     default: ''  
  tasks:
    - name: s2i-php
      params:
        - name: VERSION
          value: 7.4-ubi8
        - name: PATH_CONTEXT
          value: .
        - name: TLSVERIFY
          value: 'true'
        - name: IMAGE
          value: >-
            image-registry.openshift-image-registry.svc:5000/MATCH_OPENSHIFT_NAMESPACE/$(params.GIT_REPO_NAME)
        - name: BUILDER_IMAGE
          value: >-
            registry.redhat.io/rhel8/buildah@sha256:e19cf23d5f1e0608f5a897f0a50448beb9f8387031cca49c7487ec71bd91c4d3
      runAfter:
        - git-clone
      taskRef:
        kind: ClusterTask
        name: s2i-php
      workspaces:
        - name: source
          workspace: shared_data
    - name: git-clone
      params:
        - name: url
          value: "$(params.GIT_URL)"
        - name: revision
          value: "$(params.GIT_BRANCH)"
        - name: subdirectory
          value: "$(params.GIT_PATH_CONTEXT)"
        - name: submodules
          value: 'true'
        - name: depth
          value: '1'
        - name: sslVerify
          value: 'true'
        - name: deleteExisting
          value: 'true'
        - name: verbose
          value: 'true'
        - name: gitInitImage
          value: >-
            registry.redhat.io/openshift-pipelines/pipelines-git-init-rhel8@sha256:af7dd5b3b1598a980f17d5f5d3d8a4b11ab4f5184677f7f17ad302baa36bd3c1
        - name: userHome
          value: /tekton/home
      taskRef:
        kind: ClusterTask
        name: git-clone
      workspaces:
        - name: output
          workspace: shared_data
  finally:
    - name: openshift-client
      params:
        - name: SCRIPT
          value: oc rollout restart deployment/$(params.GIT_REPO_NAME)
        - name: VERSION
          value: latest
      taskRef:
        kind: ClusterTask
        name: openshift-client
  workspaces:
    - name: shared_data
